services:
  - type: web
    name: shopify-mini-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: FAL_KEY
        sync: false
      - key: NODE_ENV
        value: production
      - key: AUTH_ENABLED
        value: true