import type { Question } from "./question-types"

export const QUESTIONS: Question[] = [
  {
    id: "mood-emoji",
    type: "single-choice",
    title: "What's your vibe today?",
    subtitle: "Pick an emoji that matches your energy",
    options: [
      { id: "sparkles", label: "Sparkly", emoji: "✨" },
      { id: "fire", label: "Fierce", emoji: "🔥" },
      { id: "peaceful", label: "Zen", emoji: "🌸" },
      { id: "cozy", label: "Cozy", emoji: "🤎" },
      { id: "electric", label: "Electric", emoji: "⚡" },
      { id: "dreamy", label: "Dreamy", emoji: "🌙" },
    ],
  },
  {
    id: "energy-level",
    type: "slider",
    title: "What's your energy level?",
    subtitle: "From chill vibes to high energy",
    min: 0,
    max: 100,
    step: 1,
    leftLabel: "Chill 🌊",
    rightLabel: "Electric ⚡",
    defaultValue: 50,
  },
  {
    id: "current-season-feel",
    type: "single-choice",
    title: "Which season is calling to you?",
    subtitle: "Regardless of the actual weather outside",
    options: [
      { id: "spring", label: "Spring Bloom", emoji: "🌸", color: "bg-pink-100" },
      { id: "summer", label: "Summer Heat", emoji: "☀️", color: "bg-yellow-100" },
      { id: "fall", label: "Autumn Vibes", emoji: "🍂", color: "bg-orange-100" },
      { id: "winter", label: "Winter Chill", emoji: "❄️", color: "bg-blue-100" },
    ],
  },
  {
    id: "style-elements",
    type: "multiple-choice",
    title: "What elements are speaking to you?",
    subtitle: "Choose up to 3 that catch your eye",
    maxSelections: 3,
    options: [
      { id: "minimalist", label: "Clean Lines", emoji: "⚪" },
      { id: "maximalist", label: "Bold Patterns", emoji: "🎨" },
      { id: "vintage", label: "Vintage Charm", emoji: "📻" },
      { id: "modern", label: "Modern Edge", emoji: "🔷" },
      { id: "bohemian", label: "Boho Spirit", emoji: "🌻" },
      { id: "industrial", label: "Raw Materials", emoji: "🔧" },
      { id: "romantic", label: "Soft Romance", emoji: "💐" },
      { id: "futuristic", label: "Space Age", emoji: "🚀" },
    ],
  },
  {
    id: "color-intensity",
    type: "slider",
    title: "How bold do you want to go with color?",
    subtitle: "From subtle neutrals to vibrant statements",
    min: 0,
    max: 100,
    step: 1,
    leftLabel: "Subtle 🤍",
    rightLabel: "Vibrant 🌈",
    defaultValue: 50,
  },
  {
    id: "music-mood",
    type: "single-choice",
    title: "If your style was a playlist, what would it sound like?",
    subtitle: "Let music guide your aesthetic",
    options: [
      { id: "indie-folk", label: "Indie Folk", emoji: "🎸" },
      { id: "electronic", label: "Electronic", emoji: "🎧" },
      { id: "jazz", label: "Smooth Jazz", emoji: "🎷" },
      { id: "pop", label: "Pop Hits", emoji: "💫" },
      { id: "classical", label: "Classical", emoji: "🎼" },
      { id: "rock", label: "Rock Vibes", emoji: "🤘" },
    ],
  },
]
