import type { Question } from "./question-types"

export const QUESTIONS: Question[] = [
  {
    id: "mood-emoji",
    type: "single-choice",
    title: "What's your vibe today?",
    subtitle: "Pick an emoji that matches your energy",
    options: [
      { id: "sparkles", label: "Sparkly", emoji: "✨" },
      { id: "fire", label: "Fierce", emoji: "🔥" },
      { id: "peaceful", label: "Zen", emoji: "🌸" },
      { id: "cozy", label: "Cozy", emoji: "🤎" },
      { id: "electric", label: "Electric", emoji: "⚡" },
      { id: "dreamy", label: "Dreamy", emoji: "🌙" },
    ],
  },
  {
    id: "energy-level",
    type: "slider",
    title: "What's your energy level?",
    subtitle: "From chill vibes to high energy",
    min: 0,
    max: 100,
    step: 1,
    leftLabel: "Chill 🌊",
    rightLabel: "Electric ⚡",
    defaultValue: 50,
  },
  {
    id: "current-season-feel",
    type: "single-choice",
    title: "Which season is calling to you?",
    subtitle: "Regardless of the actual weather outside",
    options: [
      { id: "spring", label: "Spring Bloom", emoji: "🌸", color: "bg-pink-100" },
      { id: "summer", label: "Summer Heat", emoji: "☀️", color: "bg-yellow-100" },
      { id: "fall", label: "Autumn Vibes", emoji: "🍂", color: "bg-orange-100" },
      { id: "winter", label: "Winter Chill", emoji: "❄️", color: "bg-blue-100" },
    ],
  },
  {
    id: "style-elements",
    type: "multiple-choice",
    title: "What elements are speaking to you?",
    subtitle: "Choose up to 3 that catch your eye",
    maxSelections: 3,
    options: [
      { id: "minimalist", label: "Clean Lines", emoji: "⚪" },
      { id: "maximalist", label: "Bold Patterns", emoji: "🎨" },
      { id: "vintage", label: "Vintage Charm", emoji: "📻" },
      { id: "modern", label: "Modern Edge", emoji: "🔷" },
      { id: "bohemian", label: "Boho Spirit", emoji: "🌻" },
      { id: "industrial", label: "Raw Materials", emoji: "🔧" },
      { id: "romantic", label: "Soft Romance", emoji: "💐" },
      { id: "futuristic", label: "Space Age", emoji: "🚀" },
    ],
  },
  {
    id: "color-intensity",
    type: "slider",
    title: "How bold do you want to go with color?",
    subtitle: "From subtle neutrals to vibrant statements",
    min: 0,
    max: 100,
    step: 1,
    leftLabel: "Subtle 🤍",
    rightLabel: "Vibrant 🌈",
    defaultValue: 50,
  },
  {
    id: "music-mood",
    type: "single-choice",
    title: "If your style was a playlist, what would it sound like?",
    subtitle: "Let music guide your aesthetic",
    options: [
      { id: "indie-folk", label: "Indie Folk", emoji: "🎸" },
      { id: "electronic", label: "Electronic", emoji: "🎧" },
      { id: "jazz", label: "Smooth Jazz", emoji: "🎷" },
      { id: "pop", label: "Pop Hits", emoji: "💫" },
      { id: "classical", label: "Classical", emoji: "🎼" },
      { id: "rock", label: "Rock Vibes", emoji: "🤘" },
    ],
  },
  {
    id: "shopping-motivation",
    type: "single-choice",
    title: "What's driving your shopping today?",
    subtitle: "What's the main reason you're browsing?",
    options: [
      { id: "treat-myself", label: "Treat Myself", emoji: "💎" },
      { id: "need-essentials", label: "Need Essentials", emoji: "🛍️" },
      { id: "gift-hunting", label: "Gift Hunting", emoji: "🎁" },
      { id: "just-browsing", label: "Just Browsing", emoji: "👀" },
      { id: "wardrobe-refresh", label: "Wardrobe Refresh", emoji: "👗" },
      { id: "special-occasion", label: "Special Occasion", emoji: "✨" },
    ],
  },
  {
    id: "budget-range",
    type: "slider",
    title: "What's your budget comfort zone?",
    subtitle: "From budget-friendly to investment pieces",
    min: 0,
    max: 100,
    step: 1,
    leftLabel: "Budget 💰",
    rightLabel: "Splurge 💸",
    defaultValue: 40,
  },
  {
    id: "personality-traits",
    type: "multiple-choice",
    title: "Which personality traits describe you?",
    subtitle: "Choose up to 3 that resonate most",
    maxSelections: 3,
    options: [
      { id: "adventurous", label: "Adventurous", emoji: "🏃" },
      { id: "creative", label: "Creative", emoji: "🎨" },
      { id: "professional", label: "Professional", emoji: "💼" },
      { id: "relaxed", label: "Relaxed", emoji: "😌" },
      { id: "trendy", label: "Trendy", emoji: "📱" },
      { id: "classic", label: "Classic", emoji: "⏳" },
      { id: "bold", label: "Bold", emoji: "🦁" },
      { id: "nurturing", label: "Nurturing", emoji: "🌱" },
    ],
  },
  {
    id: "activity-preference",
    type: "single-choice",
    title: "What's your ideal way to spend a free day?",
    subtitle: "Your preference says a lot about your style",
    options: [
      { id: "outdoor-adventure", label: "Outdoor Adventure", emoji: "🏔️" },
      { id: "cozy-home", label: "Cozy at Home", emoji: "🏠" },
      { id: "social-hangout", label: "Social Hangout", emoji: "👥" },
      { id: "creative-project", label: "Creative Project", emoji: "🎨" },
      { id: "wellness-selfcare", label: "Wellness & Self-Care", emoji: "🧘" },
      { id: "explore-city", label: "Explore the City", emoji: "🌆" },
    ],
  },
  {
    id: "comfort-level",
    type: "slider",
    title: "How important is comfort in what you wear?",
    subtitle: "From fashion-first to comfort-priority",
    min: 0,
    max: 100,
    step: 1,
    leftLabel: "Style First 👠",
    rightLabel: "Comfort First 👟",
    defaultValue: 60,
  },
  {
    id: "color-palette",
    type: "single-choice",
    title: "Which color palette speaks to you?",
    subtitle: "Colors that make you feel most yourself",
    options: [
      { id: "earth-tones", label: "Earth Tones", emoji: "🌍", color: "bg-amber-100" },
      { id: "jewel-tones", label: "Jewel Tones", emoji: "💎", color: "bg-purple-100" },
      { id: "pastels", label: "Soft Pastels", emoji: "🌸", color: "bg-pink-50" },
      { id: "monochrome", label: "Black & White", emoji: "⚫", color: "bg-gray-100" },
      { id: "bright-colors", label: "Bright & Bold", emoji: "🌈", color: "bg-rainbow" },
      { id: "deep-colors", label: "Deep & Rich", emoji: "🍷", color: "bg-red-900" },
    ],
  },
  {
    id: "lifestyle-priorities",
    type: "multiple-choice",
    title: "What matters most in your lifestyle?",
    subtitle: "Select up to 3 priorities",
    maxSelections: 3,
    options: [
      { id: "sustainability", label: "Sustainability", emoji: "🌱" },
      { id: "convenience", label: "Convenience", emoji: "⚡" },
      { id: "quality", label: "Quality", emoji: "⭐" },
      { id: "uniqueness", label: "Uniqueness", emoji: "💫" },
      { id: "value", label: "Value", emoji: "💰" },
      { id: "innovation", label: "Innovation", emoji: "🚀" },
      { id: "tradition", label: "Tradition", emoji: "🏛️" },
      { id: "community", label: "Community", emoji: "🤝" },
    ],
  },
  {
    id: "social-confidence",
    type: "slider",
    title: "How do you feel about standing out in a crowd?",
    subtitle: "Your comfort with being noticed",
    min: 0,
    max: 100,
    step: 1,
    leftLabel: "Blend In 👥",
    rightLabel: "Stand Out 🌟",
    defaultValue: 45,
  },
  {
    id: "shopping-frequency",
    type: "single-choice",
    title: "How often do you shop for new items?",
    subtitle: "Your shopping rhythm",
    options: [
      { id: "weekly", label: "Weekly", emoji: "📅" },
      { id: "monthly", label: "Monthly", emoji: "🗓️" },
      { id: "seasonally", label: "Seasonally", emoji: "🍂" },
      { id: "rarely", label: "Rarely", emoji: "🕰️" },
      { id: "impulse", label: "When I Feel Like It", emoji: "✨" },
      { id: "planned", label: "Only When Needed", emoji: "📝" },
    ],
  },
  {
    id: "inspiration-source",
    type: "single-choice",
    title: "Where do you find style inspiration?",
    subtitle: "Your go-to source for ideas",
    options: [
      { id: "social-media", label: "Social Media", emoji: "📱" },
      { id: "magazines", label: "Magazines", emoji: "📖" },
      { id: "street-style", label: "Street Style", emoji: "🚶" },
      { id: "celebrities", label: "Celebrities", emoji: "⭐" },
      { id: "friends-family", label: "Friends & Family", emoji: "👨‍👩‍👧‍👦" },
      { id: "own-creativity", label: "My Own Creativity", emoji: "💡" },
    ],
  },
  {
    id: "texture-preference",
    type: "multiple-choice",
    title: "Which textures do you gravitate toward?",
    subtitle: "Choose up to 3 that appeal to you",
    maxSelections: 3,
    options: [
      { id: "soft-cozy", label: "Soft & Cozy", emoji: "🧸" },
      { id: "smooth-sleek", label: "Smooth & Sleek", emoji: "✨" },
      { id: "textured-rough", label: "Textured & Rough", emoji: "🪨" },
      { id: "flowing-draping", label: "Flowing & Draping", emoji: "🌊" },
      { id: "structured-crisp", label: "Structured & Crisp", emoji: "📐" },
      { id: "fuzzy-plush", label: "Fuzzy & Plush", emoji: "🐑" },
      { id: "metallic-shiny", label: "Metallic & Shiny", emoji: "💫" },
      { id: "natural-organic", label: "Natural & Organic", emoji: "🌿" },
    ],
  },
  {
    id: "decision-making",
    type: "slider",
    title: "How do you typically make purchase decisions?",
    subtitle: "From quick decisions to careful consideration",
    min: 0,
    max: 100,
    step: 1,
    leftLabel: "Instant 💨",
    rightLabel: "Research 🔍",
    defaultValue: 55,
  },
  {
    id: "occasion-focus",
    type: "single-choice",
    title: "What occasion are you shopping for most?",
    subtitle: "Your primary focus right now",
    options: [
      { id: "everyday-casual", label: "Everyday Casual", emoji: "👕" },
      { id: "work-professional", label: "Work & Professional", emoji: "💼" },
      { id: "special-events", label: "Special Events", emoji: "🎉" },
      { id: "travel-vacation", label: "Travel & Vacation", emoji: "✈️" },
      { id: "home-comfort", label: "Home & Comfort", emoji: "🏠" },
      { id: "fitness-active", label: "Fitness & Active", emoji: "🏃‍♀️" },
    ],
  },
  {
    id: "brand-loyalty",
    type: "slider",
    title: "How important are brand names to you?",
    subtitle: "From brand-focused to brand-agnostic",
    min: 0,
    max: 100,
    step: 1,
    leftLabel: "Don't Care 🤷",
    rightLabel: "Very Important 🏷️",
    defaultValue: 35,
  },
]
